import { splitTourHtmlBlocks } from "./src/lib/packages/tour-html";
const html = await Bun.file("/mnt/user-uploads/pasted-2026-07-29T01-14-23-134Z.txt").text();
const { parseHTML } = await import("linkedom");
(globalThis as any).DOMParser = class { parseFromString(s: string){ return parseHTML(s).document; } };
const b = splitTourHtmlBlocks(html)[0];
const doc = new (globalThis as any).DOMParser().parseFromString(b, "text/html");
const raw = (doc.body?.textContent ?? "").replace(/\u00a0/g," ");
console.log("len", raw.length, "hasTax", raw.includes("taxas inclusas"));
const i = raw.indexOf("taxas inclusas");
console.log(JSON.stringify(raw.slice(i-50, i+80)));
