import { obterToken } from "../src/lib/integrations/oner/session.server";
import { solicitarPixOner } from "../src/lib/integrations/oner/payment.server";
const cartId = process.argv[2]!;
const token = await obterToken({} as any);
const ws = new WebSocket("wss://event.onertravel.com/production");
ws.addEventListener("open", () => ws.send(JSON.stringify({ action:"OnSubscribe", SubscriptionKey:`PAY-${cartId}`, GetLastMessage:true })));
ws.addEventListener("message", (e:any)=>console.log("WS>", String(e.data).slice(0,1500)));
ws.addEventListener("error", (e:any)=>console.log("WSERR", String(e?.message||e)));
const r = await solicitarPixOner(token!, { cartId, documentNumber:"39053344705", documentType:1, valor:574.79, purchaseForCustomer:false });
console.log("HTTP", JSON.stringify(r.call), (r.raw||"").slice(0,1500));
await new Promise(r=>setTimeout(r,45000));
process.exit(0);
