/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagarRouteImport } from './routes/pagar'
import { Route as PacotesRouteImport } from './routes/pacotes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacotesIndexRouteImport } from './routes/pacotes.index'
import { Route as AdminSegurancaRouteImport } from './routes/admin.seguranca'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPacotesRouteImport } from './routes/admin.pacotes'
import { Route as AdminLinkPagamentoRouteImport } from './routes/admin.link-pagamento'
import { Route as PacotesSlugIndexRouteImport } from './routes/pacotes.$slug.index'
import { Route as PacotesSlugCheckoutRouteImport } from './routes/pacotes.$slug.checkout'

const PagarRoute = PagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const PacotesRoute = PacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacotesIndexRoute = PacotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PacotesRoute,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacotesRoute = AdminPacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinkPagamentoRoute = AdminLinkPagamentoRouteImport.update({
  id: '/link-pagamento',
  path: '/link-pagamento',
  getParentRoute: () => AdminRoute,
} as any)
const PacotesSlugIndexRoute = PacotesSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => PacotesRoute,
} as any)
const PacotesSlugCheckoutRoute = PacotesSlugCheckoutRouteImport.update({
  id: '/$slug/checkout',
  path: '/$slug/checkout',
  getParentRoute: () => PacotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/pacotes': typeof PacotesRouteWithChildren
  '/pagar': typeof PagarRoute
  '/admin/link-pagamento': typeof AdminLinkPagamentoRoute
  '/admin/pacotes': typeof AdminPacotesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/pacotes/': typeof PacotesIndexRoute
  '/pacotes/$slug/checkout': typeof PacotesSlugCheckoutRoute
  '/pacotes/$slug/': typeof PacotesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/pagar': typeof PagarRoute
  '/admin/link-pagamento': typeof AdminLinkPagamentoRoute
  '/admin/pacotes': typeof AdminPacotesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/pacotes': typeof PacotesIndexRoute
  '/pacotes/$slug/checkout': typeof PacotesSlugCheckoutRoute
  '/pacotes/$slug': typeof PacotesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/pacotes': typeof PacotesRouteWithChildren
  '/pagar': typeof PagarRoute
  '/admin/link-pagamento': typeof AdminLinkPagamentoRoute
  '/admin/pacotes': typeof AdminPacotesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/pacotes/': typeof PacotesIndexRoute
  '/pacotes/$slug/checkout': typeof PacotesSlugCheckoutRoute
  '/pacotes/$slug/': typeof PacotesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/pacotes'
    | '/pagar'
    | '/admin/link-pagamento'
    | '/admin/pacotes'
    | '/admin/pedidos'
    | '/admin/seguranca'
    | '/pacotes/'
    | '/pacotes/$slug/checkout'
    | '/pacotes/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/pagar'
    | '/admin/link-pagamento'
    | '/admin/pacotes'
    | '/admin/pedidos'
    | '/admin/seguranca'
    | '/pacotes'
    | '/pacotes/$slug/checkout'
    | '/pacotes/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/pacotes'
    | '/pagar'
    | '/admin/link-pagamento'
    | '/admin/pacotes'
    | '/admin/pedidos'
    | '/admin/seguranca'
    | '/pacotes/'
    | '/pacotes/$slug/checkout'
    | '/pacotes/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  PacotesRoute: typeof PacotesRouteWithChildren
  PagarRoute: typeof PagarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pagar': {
      id: '/pagar'
      path: '/pagar'
      fullPath: '/pagar'
      preLoaderRoute: typeof PagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacotes': {
      id: '/pacotes'
      path: '/pacotes'
      fullPath: '/pacotes'
      preLoaderRoute: typeof PacotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacotes/': {
      id: '/pacotes/'
      path: '/'
      fullPath: '/pacotes/'
      preLoaderRoute: typeof PacotesIndexRouteImport
      parentRoute: typeof PacotesRoute
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacotes': {
      id: '/admin/pacotes'
      path: '/pacotes'
      fullPath: '/admin/pacotes'
      preLoaderRoute: typeof AdminPacotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/link-pagamento': {
      id: '/admin/link-pagamento'
      path: '/link-pagamento'
      fullPath: '/admin/link-pagamento'
      preLoaderRoute: typeof AdminLinkPagamentoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pacotes/$slug/': {
      id: '/pacotes/$slug/'
      path: '/$slug'
      fullPath: '/pacotes/$slug/'
      preLoaderRoute: typeof PacotesSlugIndexRouteImport
      parentRoute: typeof PacotesRoute
    }
    '/pacotes/$slug/checkout': {
      id: '/pacotes/$slug/checkout'
      path: '/$slug/checkout'
      fullPath: '/pacotes/$slug/checkout'
      preLoaderRoute: typeof PacotesSlugCheckoutRouteImport
      parentRoute: typeof PacotesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLinkPagamentoRoute: typeof AdminLinkPagamentoRoute
  AdminPacotesRoute: typeof AdminPacotesRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminSegurancaRoute: typeof AdminSegurancaRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLinkPagamentoRoute: AdminLinkPagamentoRoute,
  AdminPacotesRoute: AdminPacotesRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminSegurancaRoute: AdminSegurancaRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PacotesRouteChildren {
  PacotesIndexRoute: typeof PacotesIndexRoute
  PacotesSlugCheckoutRoute: typeof PacotesSlugCheckoutRoute
  PacotesSlugIndexRoute: typeof PacotesSlugIndexRoute
}

const PacotesRouteChildren: PacotesRouteChildren = {
  PacotesIndexRoute: PacotesIndexRoute,
  PacotesSlugCheckoutRoute: PacotesSlugCheckoutRoute,
  PacotesSlugIndexRoute: PacotesSlugIndexRoute,
}

const PacotesRouteWithChildren =
  PacotesRoute._addFileChildren(PacotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  PacotesRoute: PacotesRouteWithChildren,
  PagarRoute: PagarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
